version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "daily"
    target-branch: "develop"
    directory: /
