name: Spec_tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout hed-python
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --upgrade-strategy eager pip
          pip install -r requirements.txt

      - name: Spec Error Tests
        id: spec_error_tests
        continue-on-error: true
        run: |
           python -m unittest spec_tests/test_errors.py > error_results.txt

      - name: Bids Validation Test
        id: bids_validation_test
        continue-on-error: true
        run: |
           python -m unittest spec_tests/validate_bids.py > validate_bids_results.txt

      - name: Upload error test results
        uses: actions/upload-artifact@v3
        with:
          name: error-test-results
          path: error_results.txt

      - name: Upload bids test results
        uses: actions/upload-artifact@v3
        with:
          name: bids-test-results
          path: validate_bids_results.txt

      - name: Fail if Tests Failed
        if: steps.spec_error_tests.outcome == 'failure' || steps.bids_validation_test.outcome == 'failure'
        run: exit 1
